chore: update tests to account for outputs

diff --git a/.github/workflows/test-changes-to-aws-codeartifact-login-action.yaml b/.github/workflows/test-changes-to-aws-codeartifact-login-action.yaml
--- a/.github/workflows/test-changes-to-aws-codeartifact-login-action.yaml
+++ b/.github/workflows/test-changes-to-aws-codeartifact-login-action.yaml
@@ -22,18 +22,25 @@ jobs:
           role-to-assume: ${{ secrets.AWS_ROLE_DEPLOY_CODE_ARTIFACT }}
           aws-region: eu-west-2
       - name: "CodeArtifact Login"
+        id: codeartifact-login-basic
         uses: Telicent-io/aws-codeartifact-login-action@v1
         with:
           domain: telicent
           owner: ${{ secrets.AWS_ACCOUNT_ID }}
-      - name: "Fail if token unavailable"
-        if: ${{ ! env.AWS_CODEARTIFACT_TOKEN }}
+      - name: "Fail if user unavailable"
+        if: ${{ ! steps.codeartifact-login-basic.outputs.user }}
         run: |
-          echo "Failed to find AWS CodeArtifact token in environment"
+          echo "Failed to find AWS CodeArtifact user in outputs"
           exit 1
-      - name: "Pass if token found"
+      - name: "Fail if token unavailable"
+        if: ${{ ! steps.codeartifact-login-basic.outputs.token }}
         run: |
-          echo "AWS CodeArtifact token is ${AWS_CODEARTIFACT_TOKEN}"
+          echo "Failed to find AWS CodeArtifact token in outputs"
+          exit 1
+      - name: "Pass if user and token found"
+        run: |
+          echo "AWS CodeArtifact user is ${{ steps.codeartifact-login-basic.outputs.user }}"
+          echo "AWS CodeArtifact token is ${{ steps.codeartifact-login-basic.outputs.token }}"
           echo "The above token SHOULD be masked, if not please report a bug!"
 
   advanced-test:
@@ -47,24 +54,29 @@ jobs:
       contents: read
     steps:
       - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v1-node16
+        uses: aws-actions/configure-aws-credentials@v6
         with:
           role-to-assume: ${{ secrets.AWS_ROLE_DEPLOY_CODE_ARTIFACT }}
           aws-region: eu-west-2
       - name: "CodeArtifact Login"
+        id: codeartifact-login-advanced
         uses: Telicent-io/aws-codeartifact-login-action@v1
         with:
           domain: telicent
           owner: ${{ secrets.AWS_ACCOUNT_ID }}
-          user-variable: "CUSTOM_USER"
-          token-variable: "CUSTOM_TOKEN"
           token-lifetime: "1200"
-      - name: "Fail if token unavailable"
-        if: ${{ ! env.CUSTOM_TOKEN }}
+      - name: "Fail if user unavailable"
+        if: ${{ ! steps.codeartifact-login-advanced.outputs.user }}
         run: |
-          echo "Failed to find AWS CodeArtifact token in environment"
+          echo "Failed to find AWS CodeArtifact user in outputs"
           exit 1
-      - name: "Pass if token found"
+      - name: "Fail if token unavailable"
+        if: ${{ ! steps.codeartifact-login-advanced.outputs.token }}
         run: |
-          echo "AWS CodeArtifact token is ${CUSTOM_TOKEN}"
+          echo "Failed to find AWS CodeArtifact token in outputs"
+          exit 1
+      - name: "Pass if user and token found"
+        run: |
+          echo "AWS CodeArtifact user is ${{ steps.codeartifact-login-advanced.outputs.user }}"
+          echo "AWS CodeArtifact token is ${{ steps.codeartifact-login-advanced.outputs.token }}"
           echo "The above token SHOULD be masked, if not please report a bug!"
